# config.yaml
model_list:
  - model_name: gpt-5-from-config
    litellm_params:
      model: gpt-5
      custom_llm_provider: openai
      litellm_credential_name: telus-fuel-ix  # setup from the UI
      # api_key: ${API_KEY}
      # TODO - fix the model configration to work without manual additional from UI. At the moment models are added from the UI, which is not ideal.

litellm_settings:
  set_verbose: true
  json_logs: true

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  ssl_verify: false