# config.yaml
model_list:
  - model_name: gpt-5-from-config
    litellm_params:
      model: gpt-5
      api_key: ${API_KEY}

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  ssl_verify: false

litellm_settings:
  set_verbose: true
  json_logs: true