# config.yaml
model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: gpt-4.1
      api_key: ${API_KEY}
      api_base: ${API_BASE}

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  ssl_verify: false

litellm_settings:
  set_verbose: true
  json_logs: true